notifications:
  email: false

env:
  global:
  - TERM=dumb
  - secure: kkxhc9xpa/Njzs/5n3XYF4uMMa/Epp4WmqRRmbEQ3RfjIrHDuqq3QGU4i7JH082jD0XuPlCpf/4CY07jq0BS2KGrEsa9caOpwR+NXPP6105kbBQBkqgpmI4aHdfkb3oBdaswGuUqfXsLzRYnraWTpMPW4vinIcpJ82rPBJYmNE2LEMlHlV2Wxm1LOjpCccbdYdL7i8ujoUyyv4NcfG17YxhlovwVprexx5DwVtk27NFiJkIpCJ8hdautCjFbPMbiMxXu3upU2MQLm+qVXFDaclK9d9R5ZNtbiWS9WyyoOUXrS/bqic8SThsks7pVxnV8oUm/n7ta3ZOwrBlnqk/+yzPeeLTMpdwvxKDU3YO+Z4vz4LcHurke3ExWq+lAX0L6QIjkJMzNLUP/cBwdvlLScIobtwimIK/3MaVXFFu8pn7tTiDG7jNlED1WJjMUp9jH7XYqQSacJ58nvmmnJ0hJu9BHW7cY4snKiu2ccMyYeXrWYPKYo5xFqWbD871F5TzGRTWDKx38IZJeH9U+RGu+1LgeZIxnST43Qm9CCJDNST7/sEsMLcGhkx8L+LXrbRMehZwWBBBZ9xIsVJ7p9spSbtxay4PL28iozzdOZr5u8rUi2kwNkHKs7wgzyE8CwP4wwxg4pV2noR3lmbm7lmJKjt9siXCchmX0ONQkFZ93NpY=

language: java
jdk: oraclejdk8

service:
- docker

addons:
  apt:
    update: true
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - libappindicator1
    - fonts-liberation
    - bash
    - curl
    - libxml2-utils
    - docker-ce

install: true
before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
#
- sudo add-apt-repository universe -y >/dev/null
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list >/dev/null
- sudo apt-get update -yqq >/dev/null
- sudo apt-get install -yqq --no-install-suggests --no-install-recommends
  tree jq python-pip curl bash sudo >/dev/null
#
- sudo pip install docker-compose httpie >/dev/null 2>&1
#
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 3000 80 >/dev/null
#
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - >/dev/null
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list >/dev/null
- sudo apt-get update -yqq >/dev/null
- sudo apt-get install -yqq --no-install-suggests --no-install-recommends yarn >/dev/null

script:
- export root=$(pwd)
#
- bash gradlew >/dev/null
- java -jar ./build/libs/*.jar &
- wait_for 8080
- http :8080
- http post :8080/api
- http :8080/api
- stop_any 8080 80
#
- bash ./build/libs/*.jar &
- wait_for 8080
- http :8080
- http post :8080/api
- http :8080/api
- stop_any 8080 80
#
- bash gradlew composeUp
- http :8080/
- http post :8080/api
- http :8080/api
- bash gradlew composeDown
#
- bash mvnw >/dev/null
- java -jar ./target/*.jar &
- wait_for 8080
- http :8080/
- http post :8080/api
- http :8080/api
- stop_any 8080 80
#
- bash ./target/*.jar &
- wait_for 8080
- http post :8080/api
- http :8080/api
- http :8080/
- stop_any 8080 80
#
- bash mvnw docker-compose:up -P docker
- sleep 20
- http post :8080/api
- http :8080/api
- http :8080/
- bash mvnw docker-compose:down -P docker

before_deploy:
- cd ${root}
- ./mvnw -Pdocs
- mkdir -p ./target/generated-docs
- cp -Rf ./target/generated-docs/index.html ./target/generated-docs/404.html

deploy:
  provider: pages
  skip-cleanup: true
  # travis encrypt GITHUB_TOKEN=<your github repo token> --add
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: target/generated-docs
  target_branch: gh-pages

before_cache:
- for item in $(find ~/.gradle -name "*.lock");
    do sudo rm -rf $item ;
  done

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.docker
